services:
  runtime:
    container_name: runtime
    image: devmachines/runtime
    environment:
      CPU: "2"
      MEMORY: "2G"
      STORAGE: "10G"
      USER: "user"
      PASSWORD: "pass"
      SSH_KEYS: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICeyDWnYtatyEiHKjT/jpLUA7FLMoe97ItrkaLA2cYsX qemu_machine"
    volumes:
      - ./disks:/disks
      - image:/image:ro
    # cap_add:
    #   - NET_ADMIN
    # devices:
    #   - "/dev/net/tun"
    #   - "/dev/kvm"
    networks:
      - net1
      - net2
    depends_on:
      ubuntu:
        condition: service_completed_successfully
    stop_grace_period: 60s
    privileged: true

  ubuntu:
    image: devmachines/ubuntu:noble
    volumes:
      - image:/image

  novnc:
    image: devmachines/novnc
    ports:
      - "6080:6080"
    networks:
      - net2
    command: novnc_server --vnc runtime:5977

networks:
  net1: {}
  net2: {}

volumes:
  image: {}
