services:
  runtime:
    container_name: runtime
    image: devmachines/runtime
    environment:
      CPU: "2"
      MEMORY: "2G"
      STORAGE: "10G"
      USER: "user"
      PASSWORD: "pass"
      SSH_KEYS: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICeyDWnYtatyEiHKjT/jpLUA7FLMoe97ItrkaLA2cYsX qemu_machine"
      VNC: ":77"
      PORTS: "2222:22"
    volumes:
      - ./disks:/disks
      - ./socks:/socks
      - type: image
        source: devmachines/ubuntu:noble
        target: /image
        read_only: true
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
      - "/dev/kvm"
    ports:
      - "2222:2222"
      - "8080:8080"
    stop_grace_period: 60s

  novnc:
    image: devmachines/novnc
    ports:
      - "6080:6080"
    command: novnc_server --vnc runtime:5977
