services:
  runtime:
    container_name: runtime
    image: devmachines/runtime
    environment:
      CPU: "2"
      MEMORY: "2G"
      STORAGE: "10G"
      USER: "user"
      PASSWORD: "pass"
      SSH_KEYS: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICeyDWnYtatyEiHKjT/jpLUA7FLMoe97ItrkaLA2cYsX qemu_machine"
    volumes:
      - ./disks:/disks
      - socks:/socks
      - type: image
        source: devmachines/ubuntu:noble
        target: /image
        read_only: true
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
      - "/dev/kvm"
    ports:
      - "2222:2222"
    stop_grace_period: 60s

  novnc:
    image: devmachines/novnc
    ports:
      - "8080:6080"
    command: novnc_server

  websockify:
    image: devmachines/novnc
    volumes:
      - socks:/socks
    ports:
      - "6080:6080"
    command: websockify --unix-target=/socks/vnc.sock 0.0.0.0:6080

volumes:
  socks: {}
