services:
  runtime:
    container_name: runtime
    image: devmachines/runtime
    volumes:
      - ./blobs:/blobs
      - image:/image:ro
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
      - "/dev/kvm"
    depends_on:
      ubuntu:
        condition: service_completed_successfully

  ubuntu:
    image: devmachines/ubuntu
    volumes:
      - image:/image

volumes:
  image: {}
