# TODO: remove privileged: /dev/kvm, /dev/net/tun, NET_ADMIN
# IDEA: may be need 2 networks

services:
  runtime:
    container_name: runtime
    image: devmachines/runtime
    volumes:
      - ./blobs:/blobs
      - image:/image:ro
    privileged: true
    depends_on:
      ubuntu:
        condition: service_completed_successfully

  ubuntu:
    image: devmachines/ubuntu
    volumes:
      - image:/image

volumes:
  image: {}
